export const dummyHabits = [
  {
    id: 1,
    title: "Reading a Book",
    description: "Read at least one chapter of a book",
    status: {
      Sunday: "Done",
      Saturday: "Not Done",
      Friday: "Done",
      Thursday: "Done",
      Wednesday: "Not Done",
      Tuesday: "None",
      Monday: "Done",
    },
  },
  {
    id: 2,
    title: "Going to the Gym",
    description: "Workout for at least 30 minutes",
    status: {
      Sunday: "None",
      Saturday: "Done",
      Friday: "Done",
      Thursday: "None",
      Wednesday: "Done",
      Tuesday: "Done",
      Monday: "Done",
    },
  },
  {
    id: 3,
    title: "Meditation",
    description: "Meditate for 10 minutes",
    status: {
      Sunday: "Done",
      Saturday: "Done",
      Friday: "None",
      Thursday: "None",
      Wednesday: "Done",
      Tuesday: "Done",
      Monday: "Done",
    },
  },
  {
    id: 4,
    title: "Running",
    description: "Run for 20 minutes",
    status: {
      Sunday: "Done",
      Saturday: "None",
      Friday: "Done",
      Thursday: "Done",
      Wednesday: "Done",
      Tuesday: "Not Done",
      Monday: "Done",
    },
  },
];
